async function createHighsModule(moduleArg={}){var moduleRtn;var Module=moduleArg,aa=typeof window=="object",ba=typeof WorkerGlobalScope!="undefined",l=typeof process=="object"&&process.versions?.node&&process.type!="renderer";if(l){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ca="./this.program",da=(a,b)=>{throw b;},ea=import.meta.url,fa="",ha,ia;
if(l){var fs=require("fs");ea.startsWith("file:")&&(fa=require("path").dirname(require("url").fileURLToPath(ea))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)});ha=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ka=console.log.bind(console),n=console.error.bind(console),u,la=!1,ma,ja=a=>a.startsWith("file://"),na,oa,pa,v,w,qa,y,z,ra,sa=!1;function ta(){var a=pa.buffer;v=new Int8Array(a);qa=new Int16Array(a);Module.HEAPU8=w=new Uint8Array(a);new Uint16Array(a);y=new Int32Array(a);z=new Uint32Array(a);new Float32Array(a);new Float64Array(a);ra=new BigInt64Array(a);new BigUint64Array(a)}var A=0,D=null;
function ua(a){Module.onAbort?.(a);a="Aborted("+a+")";n(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var va;async function wa(a){if(!u)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==va&&u)a=new Uint8Array(u);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),ua(d)}}async function ya(a){var b=va;if(!u&&typeof WebAssembly.instantiateStreaming=="function"&&!ja(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return xa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;a.length>0;)a.shift()(Module)},Ba=[],Ca=[],Da=()=>{var a=Module.preRun.shift();Ca.push(a)},Ea=!0,Fa=[],Ga=0,E=0;class Ha{constructor(a){this.Oa=a;this.xa=a-24}init(a,b){z[this.xa+16>>2]=0;z[this.xa+4>>2]=a;z[this.xa+8>>2]=b}}
var Ja=a=>{var b=E;if(!b)return F(0),0;var c=new Ha(b);z[c.xa+16>>2]=b;var d=z[c.xa+4>>2];if(!d)return F(0),b;for(var e of a){if(e===0||e===d)break;if(Ia(e,d,c.xa+16))return F(e),b}F(d);return b},I=()=>{var a=y[+H>>2];H+=4;return a},Ka=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},La=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Na=()=>{if(l){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Oa=a=>{(Oa=Na())(a)},Pa=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";
b=c+"/"+b;c=c.charAt(0)==="/"}b=Ka(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Qa=typeof TextDecoder!="undefined"?new TextDecoder:void 0,J=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(c-b>16&&a.buffer&&Qa)return Qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=(e&240)==224?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;e<65536?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=[],Sa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},K=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>
6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],Ba:b};Va(a,Wa)}
var Wa={open(a){var b=Ta[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ba.fsync(a.tty)},fsync(a){a.tty.Ba.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ba.Pa)throw new L(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ba.Pa(a.tty)}catch(h){throw new L(29);}if(g===void 0&&e===0)throw new L(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ba.Ma)throw new L(60);try{for(var e=0;e<d;e++)a.tty.Ba.Ma(a.tty,b[c+e])}catch(f){throw new L(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Xa={Pa(){a:{if(!Ra.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else typeof window!="undefined"&&typeof window.prompt=="function"&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}b=Array(Sa(a)+1);a=K(a,b,0,b.length);b.length=a;Ra=b}a=Ra.shift()}return a},Ma(a,b){b===null||
b===10?(ka(J(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(ka(J(a.output)),a.output=[])},Va(){return{eb:25856,gb:5,cb:191,fb:35387,bb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Wa(){return 0},Xa(){return[24,80]}},Ya={Ma(a,b){b===null||b===10?(n(J(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(n(J(a.output)),a.output=[])}},M={za:null,Aa(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&
61440)===24576||(c&61440)===4096)throw new L(63);M.za||(M.za={dir:{node:{Ea:M.va.Ea,Ca:M.va.Ca,lookup:M.va.lookup,Ga:M.va.Ga,rename:M.va.rename,unlink:M.va.unlink,rmdir:M.va.rmdir,readdir:M.va.readdir,symlink:M.va.symlink},stream:{ya:M.ta.ya}},file:{node:{Ea:M.va.Ea,Ca:M.va.Ca},stream:{ya:M.ta.ya,read:M.ta.read,write:M.ta.write,Ra:M.ta.Ra,Ta:M.ta.Ta}},link:{node:{Ea:M.va.Ea,Ca:M.va.Ca,readlink:M.va.readlink},stream:{}},Na:{node:{Ea:M.va.Ea,Ca:M.va.Ca},stream:Za}});c=$a(a,b,c,d);(c.mode&61440)===16384?
(c.va=M.za.dir.node,c.ta=M.za.dir.stream,c.ua={}):(c.mode&61440)===32768?(c.va=M.za.file.node,c.ta=M.za.file.stream,c.wa=0,c.ua=null):(c.mode&61440)===40960?(c.va=M.za.link.node,c.ta=M.za.link.stream):(c.mode&61440)===8192&&(c.va=M.za.Na.node,c.ta=M.za.Na.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ua[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},jb(a){return a.ua?a.ua.subarray?a.ua.subarray(0,a.wa):new Uint8Array(a.ua):new Uint8Array(0)},va:{Ea(a){var b={};b.dev=(a.mode&61440)===8192?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;(a.mode&61440)===16384?b.size=4096:(a.mode&61440)===32768?b.size=a.wa:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ca(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.wa!=b&&(b==0?(a.ua=null,a.wa=0):(c=a.ua,a.ua=new Uint8Array(b),c&&
a.ua.set(c.subarray(0,Math.min(b,a.wa))),a.wa=b)))},lookup(){M.Ia||(M.Ia=new L(44),M.Ia.stack="<generic error, no stack>");throw M.Ia;},Ga(a,b,c,d){return M.createNode(a,b,c,d)},rename(a,b,c){try{var d=ab(b,c)}catch(f){}if(d){if((a.mode&61440)===16384)for(var e in d.ua)throw new L(55);e=bb(d.parent.id,d.name);if(N[e]===d)N[e]=d.Fa;else for(e=N[e];e;){if(e.Fa===d){e.Fa=d.Fa;break}e=e.Fa}}delete a.parent.ua[a.name];b.ua[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,
b){delete a.ua[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=ab(a,b),d;for(d in c.ua)throw new L(55);delete a.ua[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.ua)]},symlink(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new L(28);return a.link}},ta:{read(a,b,c,d,e){var f=a.node.ua;if(e>=a.node.wa)return 0;a=Math.min(a.node.wa-e,d);if(a>8&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},
write(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.ua||a.ua.subarray)){if(f)return a.ua=b.subarray(c,c+d),a.wa=d;if(a.wa===0&&e===0)return a.ua=b.slice(c,c+d),a.wa=d;if(e+d<=a.wa)return a.ua.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.ua?a.ua.length:0;g>=f||(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g!=0&&(f=Math.max(f,256)),g=a.ua,a.ua=new Uint8Array(f),a.wa>0&&a.ua.set(g.subarray(0,a.wa),0));if(a.ua.subarray&&b.subarray)a.ua.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.ua[e+f]=b[c+f];a.wa=Math.max(a.wa,e+d);return d},ya(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.wa);if(b<0)throw new L(28);return b},Ra(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new L(43);a=a.node.ua;if(e&2||!a||a.buffer!==v.buffer){d=!0;ua();e=void 0;if(!e)throw new L(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);v.set(a,e)}}else d=!1,e=a.byteOffset;return{xa:e,ab:d}},Ta(a,b,c,
d){M.ta.write(a,b,0,d,c,!1);return 0}}},cb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},db=null,eb={},O=[],fb=1,N=null,gb=!1,hb=!0,ib={},L=class{name="ErrnoError";constructor(a){this.Da=a}},jb=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},kb=class{va={};ta={};Ha=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Aa=a.Aa;this.id=fb++;this.name=b;this.mode=c;
this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}};
function P(a,b={}){if(!a)throw new L(44);b.Ka??(b.Ka=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(h=>!!h);for(var d=db,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=Ma(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=La(e+"/"+a[f]);try{d=ab(d,a[f])}catch(h){if(h?.Da===44&&g&&b.Za)return{path:e};throw h;}!d.Ha||g&&!b.Ka||(d=d.Ha.root);if((d.mode&61440)===40960&&(!g||b.Ja)){if(!d.va.readlink)throw new L(52);
d=d.va.readlink(d);d.charAt(0)==="/"||(d=Ma(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new L(32);}function bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function ab(a,b){var c=(a.mode&61440)===16384?(c=lb(a,"x"))?c:a.va.lookup?0:2:54;if(c)throw new L(c);for(c=N[bb(a.id,b)];c;c=c.Fa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.va.lookup(a,b)}
function $a(a,b,c,d){a=new kb(a,b,c,d);b=bb(a.parent.id,a.name);a.Fa=N[b];return N[b]=a}function mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function lb(a,b){if(hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function nb(a,b){if((a.mode&61440)!==16384)return 54;try{return ab(a,b),20}catch(c){}return lb(a,"wx")}function R(a){a=O[a];if(!a)throw new L(8);return a}
function ob(a,b=-1){a=Object.assign(new jb,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!O[b])break a;throw new L(33);}a.fd=b;return O[b]=a}function pb(a,b=-1){a=ob(a,b);a.ta?.ib?.(a);return a}function qb(a,b){var c=void 0,d=c?null:a;c??=a.va.Ca;if(!c)throw new L(63);c(d,b)}var Za={open(a){a.ta=eb[a.node.rdev].ta;a.ta.open?.(a)},ya(){throw new L(70);}};function Va(a,b){eb[a]={ta:b}}
function rb(a,b){var c=b==="/";if(c&&db)throw new L(10);if(!c&&b){var d=P(b,{Ka:!1});b=d.path;d=d.node;if(d.Ha)throw new L(10);if((d.mode&61440)!==16384)throw new L(54);}b={type:a,kb:{},Sa:b,Ya:[]};a=a.Aa(b);a.Aa=b;b.root=a;c?db=a:d&&(d.Ha=b,d.Aa&&d.Aa.Ya.push(b))}function sb(a,b,c){var d=P(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new L(28);if(a==="."||a==="..")throw new L(20);var e=nb(d,a);if(e)throw new L(e);if(!d.va.Ga)throw new L(63);return d.va.Ga(d,a,b,c)}
function S(a){return sb(a,16895,0)}function tb(a,b,c){typeof c=="undefined"&&(c=b,b=438);sb(a,b|8192,c)}function ub(a,b){if(!Pa(a))throw new L(44);var c=P(b,{parent:!0}).node;if(!c)throw new L(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=nb(c,b);if(d)throw new L(d);if(!c.va.symlink)throw new L(63);c.va.symlink(c,b,a)}
function vb(a,b,c=438){if(a==="")throw new L(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");a=P(a,{Ja:!(b&131072),Za:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new L(20);}else{if(e)throw new L(31);d=sb(a,c|511,0);f=!0}if(!d)throw new L(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&(d.mode&61440)!==
16384)throw new L(54);if(!f&&(e=d?(d.mode&61440)===40960?32:(d.mode&61440)===16384&&(mb(b)!=="r"||b&576)?31:lb(d,mb(b)):44))throw new L(e);if(b&512&&!f){e=d;e=typeof e=="string"?P(e,{Ja:!0}).node:e;if((e.mode&61440)===16384)throw new L(31);if((e.mode&61440)!==32768)throw new L(28);var g=lb(e,"w");if(g)throw new L(g);qb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:{for(e=d;;){if(e===e.parent){e=e.Aa.Sa;var h=h?e[e.length-1]!=="/"?`${e}/${h}`:e+h:e;break a}h=h?`${e.name}/${h}`:e.name;e=e.parent}h=
void 0}h=ob({node:d,path:h,flags:b,seekable:!0,position:0,ta:d.ta,$a:[],error:!1});h.ta.open&&h.ta.open(h);f&&(c&=511,d=typeof d=="string"?P(d,{Ja:!0}).node:d,qb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),hb:void 0}));!Module.logReadFiles||b&1||a in ib||(ib[a]=1);return h}function wb(a,b,c){if(a.fd===null)throw new L(8);if(!a.seekable||!a.ta.ya)throw new L(70);if(c!=0&&c!=1&&c!=2)throw new L(28);a.position=a.ta.ya(a,b,c);a.$a=[]}
function T(a,b,c){a=La("/dev/"+a);var d=cb(!!b,!!c);T.Qa??(T.Qa=64);var e=T.Qa++<<8|0;Va(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,h,m){for(var k=0,p=0;p<m;p++){try{var q=b()}catch(r){throw new L(29);}if(q===void 0&&k===0)throw new L(6);if(q===null||q===void 0)break;k++;g[h+p]=q}k&&(f.node.atime=Date.now());return k},write(f,g,h,m){for(var k=0;k<m;k++)try{c(g[h+k])}catch(p){throw new L(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return k}});tb(a,d,e)}
var U={},H=void 0,xb=0,yb={},zb=a=>{ma=a;Ea||xb>0||(Module.onExit?.(a),la=!0);da(a,new za(a))},Ab=a=>{if(!la)try{if(a(),!(Ea||xb>0))try{ma=a=ma,zb(a)}catch(b){b instanceof za||b=="unwind"||da(1,b)}}catch(b){b instanceof za||b=="unwind"||da(1,b)}},Bb={},Db=()=>{if(!Cb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(typeof navigator=="object"&&navigator.language||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Bb)Bb[b]===void 0?delete a[b]:a[b]=
Bb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Cb=c}return Cb},Cb,Eb=[],Fb,V=a=>{var b=Eb[a];b||(Eb[a]=b=Fb.get(a));return b},Hb=(a,b,c,d)=>{var e={string:k=>{var p=0;if(k!==null&&k!==void 0&&k!==0){p=Sa(k)+1;var q=Gb(p);K(k,w,q,p);p=q}return p},array:k=>{var p=Gb(k.length);v.set(k,p);return p}};a=Module["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var m=e[c[h]];m?(g===0&&(g=W()),f[h]=m(d[h])):f[h]=d[h]}c=a(...f);return c=function(k){g!==0&&X(g);return b==="string"?k?J(w,k):"":b==="boolean"?
!!k:k}(c)};N=Array(4096);rb(M,"/");S("/tmp");S("/home");S("/home/web_user");(function(){S("/dev");Va(259,{read:()=>0,write:(d,e,f,g)=>g,ya:()=>0});tb("/dev/null",259);Ua(1280,Xa);Ua(1536,Ya);tb("/dev/tty",1280);tb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(Oa(a),b=a.byteLength);return a[--b]};T("random",c);T("urandom",c);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");rb({Aa(){var b=$a(a,"fd",16895,73);b.ta={ya:M.ta.ya};b.va={lookup(c,d){c=+d;var e=R(c);c={parent:null,Aa:{Sa:"fake"},va:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(O.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();Module.noExitRuntime&&(Ea=Module.noExitRuntime);Module.print&&(ka=Module.print);Module.printErr&&(n=Module.printErr);Module.wasmBinary&&(u=Module.wasmBinary);
Module.thisProgram&&(ca=Module.thisProgram);Module.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>f==="number"||f==="boolean");return b!=="string"&&e&&!d?Module["_"+a]:(...f)=>Hb(a,b,c,f)};
var Ib,Y,F,X,Gb,W,Jb,Kb,Ia,Lb,dc={m:a=>{var b=new Ha(a);v[b.xa+12]==0&&(v[b.xa+12]=1,Ga--);v[b.xa+13]=0;Fa.push(b);Jb(a);return Lb(a)},p:()=>{Y(0,0);var a=Fa.pop();Kb(a.Oa);E=0},b:()=>Ja([]),g:a=>Ja([a]),L:()=>{var a=Fa.pop();a||ua("no exception to throw");var b=a.Oa;v[a.xa+13]==0&&(Fa.push(a),v[a.xa+13]=1,v[a.xa+12]=0,Ga++);E=b;throw E;},h:(a,b,c)=>{(new Ha(a)).init(b,c);E=a;Ga++;throw E;},N:()=>Ga,d:a=>{E||=a;throw E;},v:function(a,b,c){H=c;try{var d=R(a);switch(b){case 0:var e=I();if(e<0)break;
for(;O[e];)e++;return pb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=I(),d.flags|=e,0;case 12:return e=I(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof U=="undefined"||f.name!=="ErrnoError")throw f;return-f.Da}},z:function(a,b,c){H=c;try{var d=R(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ba.Va){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=I();y[e>>2]=25856;y[e+4>>2]=5;y[e+
8>>2]=191;y[e+12>>2]=35387;for(var f=0;f<32;f++)v[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ba.Wa)for(e=I(),a=[],f=0;f<32;f++)a.push(v[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=I();return y[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=I();if(!d.ta.Ua)throw new L(59);return d.ta.Ua(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ba.Xa&&(f=[24,80],e=I(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);
return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof U=="undefined"||g.name!=="ErrnoError")throw g;return-g.Da}},A:function(a,b,c,d){H=d;try{b=b?J(w,b):"";var e=b;if(e.charAt(0)==="/")b=e;else{var f=a===-100?"/":R(a).path;if(e.length==0)throw new L(44);b=f+"/"+e}var g=d?I():0;return vb(b,c,g).fd}catch(h){if(typeof U=="undefined"||h.name!=="ErrnoError")throw h;return-h.Da}},Q:()=>ua(""),F:()=>{Ea=!1;xb=0},H:(a,b)=>{yb[a]&&(clearTimeout(yb[a].id),
delete yb[a]);if(!b)return 0;var c=setTimeout(()=>{delete yb[a];Ab(()=>Ib(a,performance.now()))},b);yb[a]={id:c,lb:b};return 0},I:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z[a>>2]=Math.max(f,e)*60;y[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${g>=0?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(K(a,w,c,17),K(b,w,d,17)):(K(a,w,d,17),K(b,w,c,17))},M:function(a,
b,c){if(!(a>=0&&a<=3))return 28;ra[c>>3]=BigInt(Math.round((a===0?Date.now():performance.now())*1E3*1E3));return 0},r:()=>performance.now(),G:a=>{var b=w.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},J:(a,b)=>{var c=0,d=0,e;for(e of Db()){var f=b+c;z[a+d>>2]=f;c+=
K(e,w,f,Infinity)+1;d+=4}return 0},K:(a,b)=>{var c=Db();z[a>>2]=c.length;a=0;for(var d of c)a+=Sa(d)+1;z[b>>2]=a;return 0},y:function(a){try{var b=R(a);if(b.fd===null)throw new L(8);b.La&&(b.La=null);try{b.ta.close&&b.ta.close(b)}catch(c){throw c;}finally{O[b.fd]=null}b.fd=null;return 0}catch(c){if(typeof U=="undefined"||c.name!=="ErrnoError")throw c;return c.Da}},P:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var f,g=b=0;g<c;g++){var h=z[a>>2],m=z[a+4>>2];a+=8;var k=e,p=h,q=m,r=f,t=v;if(q<0||r<0)throw new L(28);
if(k.fd===null)throw new L(8);if((k.flags&2097155)===1)throw new L(8);if((k.node.mode&61440)===16384)throw new L(31);if(!k.ta.read)throw new L(28);var x=typeof r!="undefined";if(!x)r=k.position;else if(!k.seekable)throw new L(70);var B=k.ta.read(k,t,p,q,r);x||(k.position+=B);var C=B;if(C<0){var G=-1;break a}b+=C;if(C<m)break;typeof f!="undefined"&&(f+=C)}G=b}z[d>>2]=G;return 0}catch(Q){if(typeof U=="undefined"||Q.name!=="ErrnoError")throw Q;return Q.Da}},O:function(a,b,c,d){b=b<-9007199254740992||
b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 61;var e=R(a);wb(e,b,c);ra[d>>3]=BigInt(e.position);e.La&&b===0&&c===0&&(e.La=null);return 0}catch(f){if(typeof U=="undefined"||f.name!=="ErrnoError")throw f;return f.Da}},B:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var f,g=b=0;g<c;g++){var h=z[a>>2],m=z[a+4>>2];a+=8;var k=e,p=h,q=m,r=f,t=v;if(q<0||r<0)throw new L(28);if(k.fd===null)throw new L(8);if((k.flags&2097155)===0)throw new L(8);if((k.node.mode&61440)===16384)throw new L(31);if(!k.ta.write)throw new L(28);
k.seekable&&k.flags&1024&&wb(k,0,2);var x=typeof r!="undefined";if(!x)r=k.position;else if(!k.seekable)throw new L(70);var B=k.ta.write(k,t,p,q,r,void 0);x||(k.position+=B);var C=B;if(C<0){var G=-1;break a}b+=C;if(C<m)break;typeof f!="undefined"&&(f+=C)}G=b}z[d>>2]=G;return 0}catch(Q){if(typeof U=="undefined"||Q.name!=="ErrnoError")throw Q;return Q.Da}},a:Mb,c:Nb,j:Ob,D:Pb,u:Qb,o:Rb,w:Sb,t:Tb,C:Ub,x:Vb,f:Wb,l:Xb,e:Yb,n:Zb,i:$b,k:ac,q:bc,s:cc,E:zb},Z=await (async function(){function a(c){Z=
c.exports;pa=Z.R;ta();Fb=Z.sa;c=Z;Module._Highs_create=c.T;Module._Highs_destroy=c.U;Module._Highs_run=c.V;Module._Highs_passLp=c.W;Module._Highs_passMip=c.X;Module._Highs_setBoolOptionValue=c.Y;Module._Highs_setIntOptionValue=c.Z;Module._Highs_setDoubleOptionValue=c._;Module._Highs_setStringOptionValue=c.$;Module._Highs_getSolution=c.aa;Module._Highs_getModelStatus=c.ba;Module._Highs_changeObjectiveSense=c.ca;Module._Highs_call=c.da;Module._Highs_getNumCols=c.ea;Module._Highs_getNumRows=c.fa;Ib=
c.ga;Module._malloc=c.ha;Module._free=c.ia;Y=c.ja;F=c.ka;X=c.la;Gb=c.ma;W=c.na;Jb=c.oa;Kb=c.pa;Ia=c.qa;Lb=c.ra;A--;Module.monitorRunDependencies?.(A);A==0&&D&&(c=D,D=null,c());return Z}A++;Module.monitorRunDependencies?.(A);var b={a:dc};if(Module.instantiateWasm)return new Promise(c=>{Module.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=Module.locateFile?Module.locateFile?Module.locateFile("highs.wasm",fa):fa+"highs.wasm":(new URL("highs.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await ya(b))}());
function Mb(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Wb(a){var b=W();try{V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function Nb(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Ob(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function $b(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}
function Yb(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Xb(a,b){var c=W();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Vb(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0);return 0n}}function Qb(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(h){X(g);if(h!==h+0)throw h;Y(1,0)}}function Pb(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(h){X(g);if(h!==h+0)throw h;Y(1,0)}}
function Ub(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Sb(a,b,c,d,e,f,g,h){var m=W();try{return V(a)(b,c,d,e,f,g,h)}catch(k){X(m);if(k!==k+0)throw k;Y(1,0)}}function ac(a,b,c,d,e,f,g,h){var m=W();try{V(a)(b,c,d,e,f,g,h)}catch(k){X(m);if(k!==k+0)throw k;Y(1,0)}}function Rb(a,b,c,d,e,f,g){var h=W();try{return V(a)(b,c,d,e,f,g)}catch(m){X(h);if(m!==m+0)throw m;Y(1,0)}}
function Tb(a,b,c,d,e,f,g,h,m,k,p,q){var r=W();try{return V(a)(b,c,d,e,f,g,h,m,k,p,q)}catch(t){X(r);if(t!==t+0)throw t;Y(1,0)}}function bc(a,b,c,d,e,f,g,h,m,k,p){var q=W();try{V(a)(b,c,d,e,f,g,h,m,k,p)}catch(r){X(q);if(r!==r+0)throw r;Y(1,0)}}function Zb(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function cc(a,b,c,d,e,f,g,h,m,k,p,q,r,t,x,B){var C=W();try{V(a)(b,c,d,e,f,g,h,m,k,p,q,r,t,x,B)}catch(G){X(C);if(G!==G+0)throw G;Y(1,0)}}
function ec(){function a(){Module.calledRun=!0;if(!la){sa=!0;if(!Module.noFSInit&&!gb){var b,c;gb=!0;b??=Module.stdin;c??=Module.stdout;d??=Module.stderr;b?T("stdin",b):ub("/dev/tty","/dev/stdin");c?T("stdout",null,c):ub("/dev/tty","/dev/stdout");d?T("stderr",null,d):ub("/dev/tty1","/dev/stderr");vb("/dev/stdin",0);vb("/dev/stdout",1);vb("/dev/stderr",1)}Z.S();hb=!1;na?.(Module);Module.onRuntimeInitialized?.();if(Module.postRun)for(typeof Module.postRun=="function"&&(Module.postRun=[Module.postRun]);Module.postRun.length;){var d=
Module.postRun.shift();Ba.push(d)}Aa(Ba)}}if(A>0)D=ec;else{if(Module.preRun)for(typeof Module.preRun=="function"&&(Module.preRun=[Module.preRun]);Module.preRun.length;)Da();Aa(Ca);A>0?D=ec:Module.setStatus?(Module.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>Module.setStatus(""),1);a()},1)):a()}}if(Module.preInit)for(typeof Module.preInit=="function"&&(Module.preInit=[Module.preInit]);Module.preInit.length>0;)Module.preInit.shift()();ec();window.Highs_call=Module._Highs_call;
window.Highs_changeObjectiveSense=Module._Highs_changeObjectiveSense;window.Highs_create=Module._Highs_create;window.Highs_destroy=Module._Highs_destroy;window.Highs_getModelStatus=Module._Highs_getModelStatus;window.Highs_getNumCols=Module._Highs_getNumCols;window.Highs_getNumRows=Module._Highs_getNumRows;window.Highs_getSolution=Module._Highs_getSolution;window.Highs_run=Module._Highs_run;window.Highs_setBoolOptionValue=Module.cwrap("Highs_setBoolOptionValue","number",["number","string","number"]);
window.Highs_setDoubleOptionValue=Module.cwrap("Highs_setDoubleOptionValue","number",["number","string","number"]);window.Highs_setIntOptionValue=Module.cwrap("Highs_setIntOptionValue","number",["number","string","number"]);window.Highs_setStringOptionValue=Module.cwrap("Highs_setIntOptionValue","number",["number","string","number"]);
window.Highs_passLp=function(a,b,c,d,e,f,g,h,m,k,p,q,r,t,x){var B=Module._malloc(h.length*h.BYTES_PER_ELEMENT);Module.HEAPU8.set(h,B);h=Module._malloc(m.length*m.BYTES_PER_ELEMENT);Module.HEAPU8.set(m,h);m=Module._malloc(k.length*k.BYTES_PER_ELEMENT);Module.HEAPU8.set(k,m);k=Module._malloc(p.length*p.BYTES_PER_ELEMENT);Module.HEAPU8.set(p,k);p=Module._malloc(q.length*q.BYTES_PER_ELEMENT);Module.HEAPU8.set(q,p);q=Module._malloc(r.length*r.BYTES_PER_ELEMENT);Module.HEAPU8.set(r,q);r=Module._malloc(t.length*
t.BYTES_PER_ELEMENT);Module.HEAPU8.set(t,r);t=Module._malloc(x.length*x.BYTES_PER_ELEMENT);Module.HEAPU8.set(x,t);a=Module._Highs_passLp(a,b,c,d,e,f,g,B,h,m,k,p,q,r,t);Module._free(B);Module._free(h);Module._free(m);Module._free(k);Module._free(p);Module._free(q);Module._free(r);Module._free(t);return a};
window.Highs_passMip=function(a,b,c,d,e,f,g,h,m,k,p,q,r,t,x,B){var C=Module._malloc(h.length*h.BYTES_PER_ELEMENT);Module.HEAPU8.set(h,C);h=Module._malloc(m.length*m.BYTES_PER_ELEMENT);Module.HEAPU8.set(m,h);m=Module._malloc(k.length*k.BYTES_PER_ELEMENT);Module.HEAPU8.set(k,m);k=Module._malloc(p.length*p.BYTES_PER_ELEMENT);Module.HEAPU8.set(p,k);p=Module._malloc(q.length*q.BYTES_PER_ELEMENT);Module.HEAPU8.set(q,p);q=Module._malloc(r.length*r.BYTES_PER_ELEMENT);Module.HEAPU8.set(r,q);r=Module._malloc(t.length*
t.BYTES_PER_ELEMENT);Module.HEAPU8.set(t,r);t=Module._malloc(x.length*x.BYTES_PER_ELEMENT);Module.HEAPU8.set(x,t);x=Module._malloc(B.length*B.BYTES_PER_ELEMENT);Module.HEAPU8.set(B,x);a=Module._Highs_passMip(a,b,c,d,e,f,g,C,h,m,k,p,q,r,t,x);Module._free(C);Module._free(h);Module._free(m);Module._free(k);Module._free(p);Module._free(q);Module._free(r);Module._free(t);Module._free(x);return a};
window.Highs_getSolution=function(a,b,c){let d=Module._malloc(b+8),e=Module._malloc(b+8),f=Module._malloc(c+8),g=Module._malloc(c+8);a=Module._Highs_getSolution(a,d+8,e+8,f+8,g+8);let h=new Uint8Array(Module.HEAPU8.buffer,d+8,b);b=new Uint8Array(Module.HEAPU8.buffer,e+8,b);let m=new Uint8Array(Module.HEAPU8.buffer,f+8,c);c=new Uint8Array(Module.HEAPU8.buffer,g+8,c);Module._free(d);Module._free(e);Module._free(f);Module._free(g);return{ret:a,cv:h,cd:b,rv:m,rd:c}};
sa?moduleRtn=Module:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default createHighsModule;
