
var createHighsModule = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var Module=moduleArg,aa,ba;Module.ready=new Promise((a,b)=>{aa=a;ba=b});var ca=Object.assign({},Module),da="./this.program",ea="object"==typeof window,l="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",ha,ia,ja;
if(fa){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ka=require("path");l?r=ka.dirname(r)+"/":r=require("url").fileURLToPath(new URL("./",import.meta.url));ha=(b,c)=>{b=b.startsWith("file://")?new URL(b):ka.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};ja=b=>{b=ha(b,!0);b.buffer||(b=new Uint8Array(b));return b};ia=(b,c,d,e=!0)=>{b=b.startsWith("file://")?new URL(b):ka.normalize(b);fs.readFile(b,e?void 0:"utf8",
(g,h)=>{g?d(g):c(e?h.buffer:h)})};!Module.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);Module.inspect=()=>"[Emscripten Module object]"}else if(ea||l)l?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="",ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
l&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=Module.print||console.log.bind(console),x=Module.printErr||console.error.bind(console);Object.assign(Module,ca);ca=null;Module.thisProgram&&(da=Module.thisProgram);var y;
Module.wasmBinary&&(y=Module.wasmBinary);var noExitRuntime=Module.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var ma,na=!1,A,B,oa,C,D;function pa(){var a=ma.buffer;Module.HEAP8=A=new Int8Array(a);Module.HEAP16=oa=new Int16Array(a);Module.HEAP32=C=new Int32Array(a);Module.HEAPU8=B=new Uint8Array(a);Module.HEAPU16=new Uint16Array(a);Module.HEAPU32=D=new Uint32Array(a);Module.HEAPF32=new Float32Array(a);Module.HEAPF64=new Float64Array(a)}
var qa,ra=[],sa=[],ta=[];function ua(){var a=Module.preRun.shift();ra.unshift(a)}var E=0,va=null,G=null;function z(a){if(Module.onAbort)Module.onAbort(a);a="Aborted("+a+")";x(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var H;if(Module.locateFile){if(H="highs.wasm",!wa(H)){var xa=H;H=Module.locateFile?Module.locateFile(xa,r):r+xa}}else H=(new URL("highs.wasm",import.meta.url)).href;
function ya(a){try{if(a==H&&y)return new Uint8Array(y);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}function za(a){if(!y&&(ea||l)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ya(a));if(ia)return new Promise((b,c)=>{ia(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>ya(a))}
function Aa(a,b,c){return za(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{x("failed to asynchronously prepare wasm: "+d);z(d)})}
function Ba(a,b){var c=H;return y||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||c.startsWith("file://")||fa||"function"!=typeof fetch?Aa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){x("wasm streaming compile failed: "+e);x("falling back to ArrayBuffer instantiation");return Aa(c,a,b)}))}var I,Ca,Da=a=>{for(;0<a.length;)a.shift()(Module)},Ea=[],Fa=0,J=0;
function Ga(a){this.La=a;this.za=a-24;this.ib=function(b){D[this.za+4>>2]=b};this.Ka=function(){return D[this.za+4>>2]};this.hb=function(b){D[this.za+8>>2]=b};this.cb=function(b){A[this.za+12>>0]=b?1:0};this.zb=function(){return 0!=A[this.za+12>>0]};this.eb=function(b){A[this.za+13>>0]=b?1:0};this.kb=function(){return 0!=A[this.za+13>>0]};this.gb=function(b,c){this.fb(0);this.ib(b);this.hb(c)};this.fb=function(b){D[this.za+16>>2]=b};this.yb=function(){return D[this.za+16>>2]};this.Ab=function(){if(Ha(this.Ka()))return D[this.La>>
2];var b=this.yb();return 0!==b?b:this.La}}function Ia(){var a=J;if(!a)return K(0),0;var b=new Ga(a);b.fb(a);var c=b.Ka();if(!c)return K(0),a;for(var d=0;d<arguments.length;d++){var e=arguments[d];if(0===e||e===c)break;if(Ja(e,c,b.za+16))return K(e),a}K(c);return a}
var Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ma=a=>{if("/"===
a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Na=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(fa)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}z("initRandomDevice")},Oa=a=>(Oa=Na())(a);
function Pa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ka(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Qa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ra=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=
128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function Sa(a,b){var c=Array(Qa(a)+1);a=Ra(a,c,0,c.length);b&&(c.length=a);return c}
var Ta="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,M=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ta)return Ta.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
Ua=[];function Va(a,b){Ua[a]={input:[],output:[],Ea:b};Wa(a,Xa)}
var Xa={open:function(a){var b=Ua[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ea.fsync(a.tty)},fsync:function(a){a.tty.Ea.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ea.Za)throw new N(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ea.Za(a.tty)}catch(m){throw new N(29);}if(void 0===h&&0===e)throw new N(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Ea.Ra)throw new N(60);
try{for(var e=0;e<d;e++)a.tty.Ea.Ra(a.tty,b[c+e])}catch(g){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},Ya={Za:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Sa(b,!0)}return a.input.shift()},Ra:function(a,b){null===b||10===b?(la(M(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(la(M(a.output,0)),a.output=[])},mb:function(){return{Eb:25856,Gb:5,Db:191,Fb:35387,Cb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},nb:function(){return 0},ob:function(){return[24,80]}},Za={Ra:function(a,b){null===b||10===b?(x(M(a.output,0)),
a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(x(M(a.output,0)),a.output=[])}},O={Aa:null,Da:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.Aa||(O.Aa={dir:{node:{Fa:O.wa.Fa,Ba:O.wa.Ba,lookup:O.wa.lookup,Ma:O.wa.Ma,rename:O.wa.rename,unlink:O.wa.unlink,rmdir:O.wa.rmdir,readdir:O.wa.readdir,symlink:O.wa.symlink},stream:{Ha:O.xa.Ha}},file:{node:{Fa:O.wa.Fa,Ba:O.wa.Ba},stream:{Ha:O.xa.Ha,
read:O.xa.read,write:O.xa.write,Ua:O.xa.Ua,$a:O.xa.$a,bb:O.xa.bb}},link:{node:{Fa:O.wa.Fa,Ba:O.wa.Ba,readlink:O.wa.readlink},stream:{}},Va:{node:{Fa:O.wa.Fa,Ba:O.wa.Ba},stream:$a}});c=ab(a,b,c,d);16384===(c.mode&61440)?(c.wa=O.Aa.dir.node,c.xa=O.Aa.dir.stream,c.va={}):32768===(c.mode&61440)?(c.wa=O.Aa.file.node,c.xa=O.Aa.file.stream,c.ya=0,c.va=null):40960===(c.mode&61440)?(c.wa=O.Aa.link.node,c.xa=O.Aa.link.stream):8192===(c.mode&61440)&&(c.wa=O.Aa.Va.node,c.xa=O.Aa.Va.stream);c.timestamp=Date.now();
a&&(a.va[b]=c,a.timestamp=c.timestamp);return c},Hb:function(a){return a.va?a.va.subarray?a.va.subarray(0,a.ya):new Uint8Array(a.va):new Uint8Array(0)},Wa:function(a,b){var c=a.va?a.va.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.va,a.va=new Uint8Array(b),0<a.ya&&a.va.set(c.subarray(0,a.ya),0))},rb:function(a,b){if(a.ya!=b)if(0==b)a.va=null,a.ya=0;else{var c=a.va;a.va=new Uint8Array(b);c&&a.va.set(c.subarray(0,Math.min(b,a.ya)));a.ya=b}},wa:{Fa:function(a){var b=
{};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ya:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.jb=4096;b.blocks=Math.ceil(b.size/b.jb);return b},Ba:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.rb(a,b.size)},lookup:function(){throw bb[44];
},Ma:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=cb(b,c)}catch(g){}if(d)for(var e in d.va)throw new N(55);}delete a.parent.va[a.name];a.parent.timestamp=Date.now();a.name=c;b.va[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.va[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=cb(a,b),d;for(d in c.va)throw new N(55);delete a.va[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.va)a.va.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},xa:{read:function(a,b,c,d,e){var g=a.node.va;if(e>=a.node.ya)return 0;a=Math.min(a.node.ya-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===A.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.va||a.va.subarray)){if(g)return a.va=
b.subarray(c,c+d),a.ya=d;if(0===a.ya&&0===e)return a.va=b.slice(c,c+d),a.ya=d;if(e+d<=a.ya)return a.va.set(b.subarray(c,c+d),e),d}O.Wa(a,e+d);if(a.va.subarray&&b.subarray)a.va.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.va[e+g]=b[c+g];a.ya=Math.max(a.ya,e+d);return d},Ha:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ya);if(0>b)throw new N(28);return b},Ua:function(a,b,c){O.Wa(a.node,b+c);a.node.ya=Math.max(a.node.ya,b+c)},$a:function(a,b,c,d,e){if(32768!==
(a.node.mode&61440))throw new N(43);a=a.node.va;if(e&2||a.buffer!==A.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;z();b=void 0;if(!b)throw new N(48);A.set(a,b)}else c=!1,b=a.byteOffset;return{za:b,Bb:c}},bb:function(a,b,c,d){O.xa.write(a,b,0,d,c,!1);return 0}}};function db(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var eb=null,fb={},gb=[],hb=1,P=null,ib=!0,N=null,bb={},Q=(a,b={})=>{a=Pa(a);if(!a)return{path:"",node:null};b=Object.assign({Ya:!0,Sa:0},b);if(8<b.Sa)throw new N(32);a=a.split("/").filter(h=>!!h);for(var c=eb,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=cb(c,a[e]);d=L(d+"/"+a[e]);c.Na&&(!g||g&&b.Ya)&&(c=c.Na.root);if(!g||b.Xa)for(g=0;40960===(c.mode&61440);)if(c=jb(d),d=Pa(La(d),c),c=Q(d,{Sa:b.Sa+1}).node,40<g++)throw new N(32);}return{path:d,node:c}},kb=a=>{for(var b;;){if(a===
a.parent)return a=a.Da.ab,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},lb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length},cb=(a,b)=>{var c;if(c=(c=mb(a,"x"))?c:a.wa.lookup?0:2)throw new N(c,a);for(c=P[lb(a.id,b)];c;c=c.qb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.wa.lookup(a,b)},ab=(a,b,c,d)=>{a=new nb(a,b,c,d);b=lb(a.parent.id,a.name);a.qb=P[b];return P[b]=a},ob=a=>{var b=["r","w","rw"][a&3];a&512&&
(b+="w");return b},mb=(a,b)=>{if(ib)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},pb=(a,b)=>{try{return cb(a,b),20}catch(c){}return mb(a,"wx")},qb=()=>{for(var a=0;4096>=a;a++)if(!gb[a])return a;throw new N(33);},R=a=>{a=gb[a];if(!a)throw new N(8);return a},sb=(a,b=-1)=>{rb||(rb=function(){this.Ka={}},rb.prototype={},Object.defineProperties(rb.prototype,{object:{get:function(){return this.node},set:function(c){this.node=
c}},flags:{get:function(){return this.Ka.flags},set:function(c){this.Ka.flags=c}},position:{get:function(){return this.Ka.position},set:function(c){this.Ka.position=c}}}));a=Object.assign(new rb,a);-1==b&&(b=qb());a.fd=b;return gb[b]=a},$a={open:a=>{a.xa=fb[a.node.rdev].xa;a.xa.open&&a.xa.open(a)},Ha:()=>{throw new N(70);}},Wa=(a,b)=>{fb[a]={xa:b}},tb=(a,b)=>{var c="/"===b,d=!b;if(c&&eb)throw new N(10);if(!c&&!d){var e=Q(b,{Ya:!1});b=e.path;e=e.node;if(e.Na)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);
}b={type:a,Ib:{},ab:b,pb:[]};a=a.Da(b);a.Da=b;b.root=a;c?eb=a:e&&(e.Na=b,e.Da&&e.Da.pb.push(b))},T=(a,b,c)=>{var d=Q(a,{parent:!0}).node;a=Ma(a);if(!a||"."===a||".."===a)throw new N(28);var e=pb(d,a);if(e)throw new N(e);if(!d.wa.Ma)throw new N(63);return d.wa.Ma(d,a,b,c)},ub=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);T(a,b|8192,c)},vb=(a,b)=>{if(!Pa(a))throw new N(44);var c=Q(b,{parent:!0}).node;if(!c)throw new N(44);b=Ma(b);var d=pb(c,b);if(d)throw new N(d);if(!c.wa.symlink)throw new N(63);c.wa.symlink(c,
b,a)},jb=a=>{a=Q(a).node;if(!a)throw new N(44);if(!a.wa.readlink)throw new N(28);return Pa(kb(a.parent),a.wa.readlink(a))},xb=(a,b,c)=>{if(""===a)throw new N(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=L(a);try{e=Q(a,{Xa:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=T(a,
c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==ob(b)||b&512)?31:mb(e,ob(b)):44))throw new N(c);if(b&512&&!d){c=e;c="string"==typeof c?Q(c,{Xa:!0}).node:c;if(!c.wa.Ba)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=mb(c,"w"))throw new N(d);c.wa.Ba(c,{size:0,timestamp:Date.now()})}b&=-131713;e=sb({node:e,path:kb(e),
flags:b,seekable:!0,position:0,xa:e.xa,xb:[],error:!1});e.xa.open&&e.xa.open(e);!Module.logReadFiles||b&1||(wb||(wb={}),a in wb||(wb[a]=1));return e},yb=(a,b,c)=>{if(null===a.fd)throw new N(8);if(!a.seekable||!a.xa.Ha)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.xa.Ha(a,b,c);a.xb=[]},zb=()=>{N||(N=function(a,b){this.name="ErrnoError";this.node=b;this.sb=function(c){this.Ga=c};this.sb(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(a=>{bb[a]=
new N(a);bb[a].stack="<generic error, no stack>"}))},Ab,Cb=(a,b,c)=>{a=L("/dev/"+a);var d=db(!!b,!!c);Bb||(Bb=64);var e=Bb++<<8|0;Wa(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,h,m,p)=>{for(var k=0,n=0;n<p;n++){try{var t=b()}catch(v){throw new N(29);}if(void 0===t&&0===k)throw new N(6);if(null===t||void 0===t)break;k++;h[m+n]=t}k&&(g.node.timestamp=Date.now());return k},write:(g,h,m,p)=>{for(var k=0;k<p;k++)try{c(h[m+k])}catch(n){throw new N(29);}p&&(g.node.timestamp=
Date.now());return k}});ub(a,d,e)},Bb,U={},rb,wb,Db=void 0;function V(){Db+=4;return C[Db-4>>2]}
var Eb={},Gb=()=>{if(!Fb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Eb)void 0===Eb[b]?delete a[b]:a[b]=Eb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Fb=c}return Fb},Fb,Hb=a=>0===a%4&&(0!==a%100||0===a%400),Ib=[31,29,31,30,31,30,31,31,30,31,30,31],Jb=[31,28,31,30,31,30,31,31,30,31,30,31],Kb=(a,b,c,d)=>{function e(f,
q,u){for(f="number"==typeof f?f.toString():f||"";f.length<q;)f=u[0]+f;return f}function g(f,q){return e(f,q,"0")}function h(f,q){function u(F){return 0>F?-1:0<F?1:0}var w;0===(w=u(f.getFullYear()-q.getFullYear()))&&0===(w=u(f.getMonth()-q.getMonth()))&&(w=u(f.getDate()-q.getDate()));return w}function m(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),0,2);case 4:return new Date(f.getFullYear(),
0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function p(f){var q=f.Ia;for(f=new Date((new Date(f.Ja+1900,0,1)).getTime());0<q;){var u=f.getMonth(),w=(Hb(f.getFullYear())?Ib:Jb)[u];if(q>w-f.getDate())q-=w-f.getDate()+1,f.setDate(1),11>u?f.setMonth(u+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+q);break}}u=new Date(f.getFullYear()+1,0,4);q=m(new Date(f.getFullYear(),0,4));u=m(u);return 0>=h(q,f)?0>=h(u,f)?f.getFullYear()+
1:f.getFullYear():f.getFullYear()-1}var k=C[d+40>>2];d={vb:C[d>>2],ub:C[d+4>>2],Oa:C[d+8>>2],Ta:C[d+12>>2],Pa:C[d+16>>2],Ja:C[d+20>>2],Ca:C[d+24>>2],Ia:C[d+28>>2],Jb:C[d+32>>2],tb:C[d+36>>2],wb:k?k?M(B,k):"":""};c=c?M(B,c):"";k={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I",
"%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in k)c=c.replace(new RegExp(n,"g"),k[n]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");k={"%a":f=>t[f.Ca].substring(0,3),"%A":f=>t[f.Ca],"%b":f=>v[f.Pa].substring(0,3),"%B":f=>v[f.Pa],"%C":f=>g((f.Ja+1900)/100|0,2),"%d":f=>g(f.Ta,2),"%e":f=>e(f.Ta,2," "),"%g":f=>
p(f).toString().substring(2),"%G":f=>p(f),"%H":f=>g(f.Oa,2),"%I":f=>{f=f.Oa;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":f=>{for(var q=0,u=0;u<=f.Pa-1;q+=(Hb(f.Ja+1900)?Ib:Jb)[u++]);return g(f.Ta+q,3)},"%m":f=>g(f.Pa+1,2),"%M":f=>g(f.ub,2),"%n":()=>"\n","%p":f=>0<=f.Oa&&12>f.Oa?"AM":"PM","%S":f=>g(f.vb,2),"%t":()=>"\t","%u":f=>f.Ca||7,"%U":f=>g(Math.floor((f.Ia+7-f.Ca)/7),2),"%V":f=>{var q=Math.floor((f.Ia+7-(f.Ca+6)%7)/7);2>=(f.Ca+371-f.Ia-2)%7&&q++;if(q)53==q&&(u=(f.Ca+371-f.Ia)%7,4==u||3==u&&Hb(f.Ja)||
(q=1));else{q=52;var u=(f.Ca+7-f.Ia-1)%7;(4==u||5==u&&Hb(f.Ja%400-1))&&q++}return g(q,2)},"%w":f=>f.Ca,"%W":f=>g(Math.floor((f.Ia+7-(f.Ca+6)%7)/7),2),"%y":f=>(f.Ja+1900).toString().substring(2),"%Y":f=>f.Ja+1900,"%z":f=>{f=f.tb;var q=0<=f;f=Math.abs(f)/60;return(q?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":f=>f.wb,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(n in k)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),k[n](d)));c=c.replace(/\0\0/g,"%");n=Sa(c,!1);if(n.length>b)return 0;A.set(n,
a);return n.length-1},Lb=[],W=a=>{var b=Lb[a];b||(a>=Lb.length&&(Lb.length=a+1),Lb[a]=b=qa.get(a));return b};
function Mb(a,b,c,d){var e={string:k=>{var n=0;if(null!==k&&void 0!==k&&0!==k){n=Qa(k)+1;var t=Nb(n);Ra(k,B,t,n);n=t}return n},array:k=>{var n=Nb(k.length);A.set(k,n);return n}};a=Module["_"+a];var g=[],h=0;if(d)for(var m=0;m<d.length;m++){var p=e[c[m]];p?(0===h&&(h=X()),g[m]=p(d[m])):g[m]=d[m]}c=a.apply(null,g);return c=function(k){0!==h&&Y(h);return"string"===b?k?M(B,k):"":"boolean"===b?!!k:k}(c)}
function nb(a,b,c,d){a||(a=this);this.parent=a;this.Da=a.Da;this.Na=null;this.id=hb++;this.name=b;this.mode=c;this.wa={};this.xa={};this.rdev=d}Object.defineProperties(nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});zb();P=Array(4096);tb(O,"/");T("/tmp",16895,0);T("/home",16895,0);T("/home/web_user",16895,0);
(()=>{T("/dev",16895,0);Wa(259,{read:()=>0,write:(d,e,g,h)=>h});ub("/dev/null",259);Va(1280,Ya);Va(1536,Za);ub("/dev/tty",1280);ub("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Oa(a).byteLength);return a[--b]};Cb("random",c);Cb("urandom",c);T("/dev/shm",16895,0);T("/dev/shm/tmp",16895,0)})();
(()=>{T("/proc",16895,0);var a=T("/proc/self",16895,0);T("/proc/self/fd",16895,0);tb({Da:()=>{var b=ab(a,"fd",16895,73);b.wa={lookup:(c,d)=>{var e=R(+d);c={parent:null,Da:{ab:"fake"},wa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var jc={l:function(a){a=new Ga(a);a.zb()||(a.cb(!0),Fa--);a.eb(!1);Ea.push(a);Ob(a.La);return a.Ab()},n:function(){Z(0);var a=Ea.pop();Pb(a.La);J=0},b:Ia,f:Ia,y:function(){var a=Ea.pop();a||z("no exception to throw");var b=a.La;a.kb()||(Ea.push(a),a.eb(!0),a.cb(!1),Fa++);J=b;throw J;},i:function(a,b,c){(new Ga(a)).gb(b,c);J=a;Fa++;throw J;},O:function(){return Fa},d:function(a){J||(J=a);throw J;},w:function(a,b,c){Db=c;try{var d=R(a);switch(b){case 0:var e=V();return 0>e?-28:sb(d,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=V(),d.flags|=e,0;case 5:return e=V(),oa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return C[Qb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof U||"ErrnoError"!==g.name)throw g;return-g.Ga}},Q:function(a,b,c){Db=c;try{var d=R(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ea.mb){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=V();C[e>>2]=25856;C[e+4>>
2]=5;C[e+8>>2]=191;C[e+12>>2]=35387;for(var g=0;32>g;g++)A[e+g+17>>0]=b[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ea.nb)for(e=V(),b=[],g=0;32>g;g++)b.push(A[e+g+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=V();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=V();if(!d.xa.lb)throw new N(59);return d.xa.lb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ea.ob&&(g=[24,80],e=V(),oa[e>>1]=g[0],oa[e+2>>
1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return-h.Ga}},A:function(a,b,c,d){Db=d;try{b=b?M(B,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":R(a).path;if(0==e.length)throw new N(44);b=L(g+"/"+e)}var h=d?V():0;return xb(b,c,h).fd}catch(m){if("undefined"==typeof U||"ErrnoError"!==m.name)throw m;return-m.Ga}},M:()=>!0,u:()=>{z("")},N:function(){return Date.now()},r:()=>
performance.now(),H:(a,b,c)=>B.copyWithin(a,b,b+c),I:a=>{var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ma.buffer.byteLength+65535>>>16;try{ma.grow(e);pa();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1},K:(a,b)=>{var c=0;Gb().forEach(function(d,e){var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)A[e++>>0]=d.charCodeAt(g);A[e>>0]=0;c+=d.length+
1});return 0},L:(a,b)=>{var c=Gb();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});D[b>>2]=d;return 0},z:function(a){try{var b=R(a);if(null===b.fd)throw new N(8);b.Qa&&(b.Qa=null);try{b.xa.close&&b.xa.close(b)}catch(c){throw c;}finally{gb[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof U||"ErrnoError"!==c.name)throw c;return c.Ga}},P:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var m=D[a>>2],p=D[a+4>>2];a+=8;var k=e,n=m,t=p,v=g,f=A;if(0>t||0>v)throw new N(28);
if(null===k.fd)throw new N(8);if(1===(k.flags&2097155))throw new N(8);if(16384===(k.node.mode&61440))throw new N(31);if(!k.xa.read)throw new N(28);var q="undefined"!=typeof v;if(!q)v=k.position;else if(!k.seekable)throw new N(70);var u=k.xa.read(k,f,n,t,v);q||(k.position+=u);var w=u;if(0>w){var F=-1;break a}b+=w;if(w<p)break;"undefined"!==typeof g&&(g+=w)}F=b}D[d>>2]=F;return 0}catch(S){if("undefined"==typeof U||"ErrnoError"!==S.name)throw S;return S.Ga}},E:function(a,b,c,d,e){try{b=c+2097152>>>0<
4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=R(a);yb(g,b,d);Ca=[g.position>>>0,(I=g.position,1<=+Math.abs(I)?0<I?+Math.floor(I/4294967296)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];C[e>>2]=Ca[0];C[e+4>>2]=Ca[1];g.Qa&&0===b&&0===d&&(g.Qa=null);return 0}catch(h){if("undefined"==typeof U||"ErrnoError"!==h.name)throw h;return h.Ga}},B:function(a,b,c,d){try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var m=D[a>>2],p=D[a+4>>2];a+=8;var k=e,n=m,t=p,v=g,f=A;if(0>t||0>v)throw new N(28);
if(null===k.fd)throw new N(8);if(0===(k.flags&2097155))throw new N(8);if(16384===(k.node.mode&61440))throw new N(31);if(!k.xa.write)throw new N(28);k.seekable&&k.flags&1024&&yb(k,0,2);var q="undefined"!=typeof v;if(!q)v=k.position;else if(!k.seekable)throw new N(70);var u=k.xa.write(k,f,n,t,v,void 0);q||(k.position+=u);var w=u;if(0>w){var F=-1;break a}b+=w;"undefined"!==typeof g&&(g+=w)}F=b}D[d>>2]=F;return 0}catch(S){if("undefined"==typeof U||"ErrnoError"!==S.name)throw S;return S.Ga}},G:Rb,a:Sb,
c:Tb,k:Ub,F:Vb,v:Wb,p:Xb,x:Yb,t:Zb,C:$b,D:ac,h:bc,g:cc,e:dc,o:ec,j:fc,m:gc,q:hc,s:ic,J:(a,b,c,d)=>Kb(a,b,c,d)};
(function(){function a(c){c=c.exports;Module.asm=c;ma=Module.asm.R;pa();qa=Module.asm.sa;sa.unshift(Module.asm.S);E--;Module.monitorRunDependencies&&Module.monitorRunDependencies(E);if(0==E&&(null!==va&&(clearInterval(va),va=null),G)){var d=G;G=null;d()}return c}var b={a:jc};E++;Module.monitorRunDependencies&&Module.monitorRunDependencies(E);if(Module.instantiateWasm)try{return Module.instantiateWasm(b,a)}catch(c){x("Module.instantiateWasm callback failed with error: "+c),ba(c)}Ba(b,function(c){a(c.instance)}).catch(ba);
return{}})();Module._Highs_create=function(){return(Module._Highs_create=Module.asm.T).apply(null,arguments)};Module._Highs_destroy=function(){return(Module._Highs_destroy=Module.asm.U).apply(null,arguments)};Module._Highs_run=function(){return(Module._Highs_run=Module.asm.V).apply(null,arguments)};Module._Highs_passLp=function(){return(Module._Highs_passLp=Module.asm.W).apply(null,arguments)};Module._Highs_passMip=function(){return(Module._Highs_passMip=Module.asm.X).apply(null,arguments)};
Module._Highs_setBoolOptionValue=function(){return(Module._Highs_setBoolOptionValue=Module.asm.Y).apply(null,arguments)};Module._Highs_setIntOptionValue=function(){return(Module._Highs_setIntOptionValue=Module.asm.Z).apply(null,arguments)};Module._Highs_setDoubleOptionValue=function(){return(Module._Highs_setDoubleOptionValue=Module.asm._).apply(null,arguments)};Module._Highs_setStringOptionValue=function(){return(Module._Highs_setStringOptionValue=Module.asm.$).apply(null,arguments)};
Module._Highs_getSolution=function(){return(Module._Highs_getSolution=Module.asm.aa).apply(null,arguments)};Module._Highs_getModelStatus=function(){return(Module._Highs_getModelStatus=Module.asm.ba).apply(null,arguments)};Module._Highs_changeObjectiveSense=function(){return(Module._Highs_changeObjectiveSense=Module.asm.ca).apply(null,arguments)};Module._Highs_call=function(){return(Module._Highs_call=Module.asm.da).apply(null,arguments)};
Module._Highs_getNumCols=function(){return(Module._Highs_getNumCols=Module.asm.ea).apply(null,arguments)};Module._Highs_getNumRows=function(){return(Module._Highs_getNumRows=Module.asm.fa).apply(null,arguments)};function Qb(){return(Qb=Module.asm.ga).apply(null,arguments)}Module._malloc=function(){return(Module._malloc=Module.asm.ha).apply(null,arguments)};Module._free=function(){return(Module._free=Module.asm.ia).apply(null,arguments)};function Z(){return(Z=Module.asm.ja).apply(null,arguments)}
function K(){return(K=Module.asm.ka).apply(null,arguments)}function X(){return(X=Module.asm.la).apply(null,arguments)}function Y(){return(Y=Module.asm.ma).apply(null,arguments)}function Nb(){return(Nb=Module.asm.na).apply(null,arguments)}function Ob(){return(Ob=Module.asm.oa).apply(null,arguments)}function Pb(){return(Pb=Module.asm.pa).apply(null,arguments)}function Ja(){return(Ja=Module.asm.qa).apply(null,arguments)}function Ha(){return(Ha=Module.asm.ra).apply(null,arguments)}
var kc=Module.dynCall_j=function(){return(kc=Module.dynCall_j=Module.asm.ta).apply(null,arguments)},lc=Module.dynCall_iiij=function(){return(lc=Module.dynCall_iiij=Module.asm.ua).apply(null,arguments)};function bc(a){var b=X();try{W(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function Sb(a,b){var c=X();try{return W(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Ub(a,b,c,d){var e=X();try{return W(a)(b,c,d)}catch(g){Y(e);if(g!==g+0)throw g;Z(1,0)}}
function dc(a,b,c){var d=X();try{W(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function ec(a,b,c,d){var e=X();try{W(a)(b,c,d)}catch(g){Y(e);if(g!==g+0)throw g;Z(1,0)}}function Tb(a,b,c){var d=X();try{return W(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function cc(a,b){var c=X();try{W(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Yb(a,b,c,d,e,g,h,m){var p=X();try{return W(a)(b,c,d,e,g,h,m)}catch(k){Y(p);if(k!==k+0)throw k;Z(1,0)}}
function fc(a,b,c,d,e){var g=X();try{W(a)(b,c,d,e)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function gc(a,b,c,d,e,g,h,m){var p=X();try{W(a)(b,c,d,e,g,h,m)}catch(k){Y(p);if(k!==k+0)throw k;Z(1,0)}}function Xb(a,b,c,d,e,g,h){var m=X();try{return W(a)(b,c,d,e,g,h)}catch(p){Y(m);if(p!==p+0)throw p;Z(1,0)}}function Zb(a,b,c,d,e,g,h,m,p,k,n,t){var v=X();try{return W(a)(b,c,d,e,g,h,m,p,k,n,t)}catch(f){Y(v);if(f!==f+0)throw f;Z(1,0)}}
function hc(a,b,c,d,e,g,h,m,p,k,n){var t=X();try{W(a)(b,c,d,e,g,h,m,p,k,n)}catch(v){Y(t);if(v!==v+0)throw v;Z(1,0)}}function ic(a,b,c,d,e,g,h,m,p,k,n,t,v,f,q,u){var w=X();try{W(a)(b,c,d,e,g,h,m,p,k,n,t,v,f,q,u)}catch(F){Y(w);if(F!==F+0)throw F;Z(1,0)}}function Rb(a){var b=X();try{return W(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function Wb(a,b,c,d,e,g){var h=X();try{return W(a)(b,c,d,e,g)}catch(m){Y(h);if(m!==m+0)throw m;Z(1,0)}}
function Vb(a,b,c,d,e,g){var h=X();try{return W(a)(b,c,d,e,g)}catch(m){Y(h);if(m!==m+0)throw m;Z(1,0)}}function ac(a){var b=X();try{return kc(a)}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function $b(a,b,c,d,e){var g=X();try{return lc(a,b,c,d,e)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}Module.cwrap=function(a,b,c,d){var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?Module["_"+a]:function(){return Mb(a,b,c,arguments)}};var mc;G=function nc(){mc||oc();mc||(G=nc)};
function oc(){function a(){if(!mc&&(mc=!0,Module.calledRun=!0,!na)){Module.noFSInit||Ab||(Ab=!0,zb(),Module.stdin=Module.stdin,Module.stdout=Module.stdout,Module.stderr=Module.stderr,Module.stdin?Cb("stdin",Module.stdin):vb("/dev/tty","/dev/stdin"),Module.stdout?Cb("stdout",null,Module.stdout):vb("/dev/tty","/dev/stdout"),Module.stderr?Cb("stderr",null,Module.stderr):vb("/dev/tty1","/dev/stderr"),xb("/dev/stdin",0),xb("/dev/stdout",1),xb("/dev/stderr",1));ib=!1;Da(sa);aa(Module);if(Module.onRuntimeInitialized)Module.onRuntimeInitialized();
if(Module.postRun)for("function"==typeof Module.postRun&&(Module.postRun=[Module.postRun]);Module.postRun.length;){var b=Module.postRun.shift();ta.unshift(b)}Da(ta)}}if(!(0<E)){if(Module.preRun)for("function"==typeof Module.preRun&&(Module.preRun=[Module.preRun]);Module.preRun.length;)ua();Da(ra);0<E||(Module.setStatus?(Module.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Module.setStatus("")},1);a()},1)):a())}}
if(Module.preInit)for("function"==typeof Module.preInit&&(Module.preInit=[Module.preInit]);0<Module.preInit.length;)Module.preInit.pop()();oc();window.Highs_call=Module._Highs_call;window.Highs_changeObjectiveSense=Module._Highs_changeObjectiveSense;window.Highs_create=Module._Highs_create;window.Highs_destroy=Module._Highs_destroy;window.Highs_getModelStatus=Module._Highs_getModelStatus;window.Highs_getNumCols=Module._Highs_getNumCols;window.Highs_getNumRows=Module._Highs_getNumRows;
window.Highs_getSolution=Module._Highs_getSolution;window.Highs_run=Module._Highs_run;window.Highs_setBoolOptionValue=Module.cwrap("Highs_setBoolOptionValue","number",["number","string","number"]);window.Highs_setDoubleOptionValue=Module.cwrap("Highs_setDoubleOptionValue","number",["number","string","number"]);window.Highs_setIntOptionValue=Module.cwrap("Highs_setIntOptionValue","number",["number","string","number"]);
window.Highs_setStringOptionValue=Module.cwrap("Highs_setIntOptionValue","number",["number","string","number"]);
window.Highs_passLp=function(a,b,c,d,e,g,h,m,p,k,n,t,v,f,q){var u=Module._malloc(m.length*m.BYTES_PER_ELEMENT);Module.HEAP8.set(m,u);m=Module._malloc(p.length*p.BYTES_PER_ELEMENT);Module.HEAP8.set(p,m);p=Module._malloc(k.length*k.BYTES_PER_ELEMENT);Module.HEAP8.set(k,p);k=Module._malloc(n.length*n.BYTES_PER_ELEMENT);Module.HEAP8.set(n,k);n=Module._malloc(t.length*t.BYTES_PER_ELEMENT);Module.HEAP8.set(t,n);t=Module._malloc(v.length*v.BYTES_PER_ELEMENT);Module.HEAP8.set(v,t);v=Module._malloc(f.length*
f.BYTES_PER_ELEMENT);Module.HEAP8.set(f,v);f=Module._malloc(q.length*q.BYTES_PER_ELEMENT);Module.HEAP8.set(q,f);a=Module._Highs_passLp(a,b,c,d,e,g,h,u,m,p,k,n,t,v,f);Module._free(u);Module._free(m);Module._free(p);Module._free(k);Module._free(n);Module._free(t);Module._free(v);Module._free(f);return a};
window.Highs_passMip=function(a,b,c,d,e,g,h,m,p,k,n,t,v,f,q,u){var w=Module._malloc(m.length*m.BYTES_PER_ELEMENT);Module.HEAP8.set(m,w);m=Module._malloc(p.length*p.BYTES_PER_ELEMENT);Module.HEAP8.set(p,m);p=Module._malloc(k.length*k.BYTES_PER_ELEMENT);Module.HEAP8.set(k,p);k=Module._malloc(n.length*n.BYTES_PER_ELEMENT);Module.HEAP8.set(n,k);n=Module._malloc(t.length*t.BYTES_PER_ELEMENT);Module.HEAP8.set(t,n);t=Module._malloc(v.length*v.BYTES_PER_ELEMENT);Module.HEAP8.set(v,t);v=Module._malloc(f.length*
f.BYTES_PER_ELEMENT);Module.HEAP8.set(f,v);f=Module._malloc(q.length*q.BYTES_PER_ELEMENT);Module.HEAP8.set(q,f);q=Module._malloc(u.length*u.BYTES_PER_ELEMENT);Module.HEAP8.set(u,q);a=Module._Highs_passMip(a,b,c,d,e,g,h,w,m,p,k,n,t,v,f,q);Module._free(w);Module._free(m);Module._free(p);Module._free(k);Module._free(n);Module._free(t);Module._free(v);Module._free(f);Module._free(q);return a};
window.Highs_getSolution=function(a,b,c){let d=Module._malloc(b+8),e=Module._malloc(b+8),g=Module._malloc(c+8),h=Module._malloc(c+8);a=Module._Highs_getSolution(a,d+8,e+8,g+8,h+8);let m=new Uint8Array(Module.HEAPU8.buffer,d+8,b);b=new Uint8Array(Module.HEAPU8.buffer,e+8,b);let p=new Uint8Array(Module.HEAPU8.buffer,g+8,c);c=new Uint8Array(Module.HEAPU8.buffer,h+8,c);Module._free(d);Module._free(e);Module._free(g);Module._free(h);return{ret:a,cv:m,cd:b,rv:p,rd:c}};


  return moduleArg.ready
}

);
})();
export default createHighsModule;