[config]
default_to_workspace = false

[env]
GIT_DESCRIBE = { script = ["git describe --dirty --always --tags"] }

[env.development]
TARGET_SUBDIRECTORY = "debug"

[env.release]
TARGET_SUBDIRECTORY = "release"

[tasks.build-wasm]
script = '''
mkdir -p dist
cargo build --target wasm32-unknown-unknown --profile ${CARGO_MAKE_CARGO_PROFILE}
wasm-bindgen --out-dir dist --no-typescript --target web target/wasm32-unknown-unknown/${TARGET_SUBDIRECTORY}/homotopy_web.wasm
'''

[tasks.build-wasm-watch]
run_task = { name = ["build-wasm"] }
watch = { watch = ["homotopy-common/src", "homotopy-core/src", "homotopy-graphics/src", "homotopy-web/src", "homotopy-model/src", "homotopy-gl/src"] }

[tasks.build-highs]
script = '''
mkdir -p dist
cp -f $(nix build .#highs --no-link --print-out-paths --extra-experimental-features flakes --extra-experimental-features nix-command)/highs.{js,wasm} dist/
'''

[tasks.build-server]
script = '''
mkdir -p homotopy-server/dist
cargo build -p homotopy-server --target wasm32-unknown-unknown --profile ${CARGO_MAKE_CARGO_PROFILE}
wasm-bindgen --out-dir homotopy-server/dist --no-typescript --target nodejs target/wasm32-unknown-unknown/${TARGET_SUBDIRECTORY}/homotopy_server.wasm
'''

[tasks.build-server-watch]
run_task = { name = ["build-server"] }
watch = { watch = ["homotopy-server/src", "homotopy-server/Cargo.toml"] }

[tasks.dist-static]
script = '''
mkdir -p dist
echo "Cleaning old files"
find dist \
    ! -name highs.js \
    ! -name highs.wasm \
    ! -name homotopy_web.js \
    ! -name homotopy_web_bg.wasm \
    -type f -exec rm -f {} +
cp -r homotopy-web/static/* dist/
ls dist
'''

[tasks.dist-static-watch]
run_task = { name = ["dist-static"] }
watch = { watch = ["homotopy-web/static"] }

[tasks.dist]
run_task = { name = ["build-wasm", "dist-static"] }

[tasks.clean]
clear = true
script = '''
rm -rf dist
cargo clean
'''

[tasks.mkdir-dist]
script = '''
mkdir -p dist
'''

[tasks.devserver]
command = "devserver"
args = [
  "--path"
, "dist"
, "--header"
, "Cross-Origin-Opener-Policy=same-origin"
, "--header"
, "Cross-Origin-Embedder-Policy=require-corp"
]

# for testing Firebase components locally
[tasks.firebase-emulator]
command = "firebase"
args = [
  "emulators:start"
]

[tasks.firebase-emulator-functions]
command = "firebase"
args = [
  "emulators:start",
  "--only",
  "functions"
]
watch = { watch = ["homotopy-server/dist"] }

[tasks.serve]
run_task = { name = ["build-highs", "dist-static-watch", "build-wasm-watch", "devserver"], fork = true, parallel = true }

[tasks.emulate-server]
run_task = { name = ["build-server-watch", "firebase-emulator-functions"], fork = true, parallel = true }
