[env]
GIT_DESCRIBE = { script = ["git describe --dirty --always --tags"] }

[env.development]
WASM_PACK_FLAGS = "--dev"

[env.production]
WASM_PACK_FLAGS = "--release"

[tasks.build-wasm]
script = '''
mkdir -p dist
wasm-pack build --target web --no-typescript ${WASM_PACK_FLAGS}
mv pkg/homotopy_web.js pkg/homotopy_web_bg.wasm dist
rm -rf pkg
'''

[tasks.build-wasm-watch]
run_task = { name = ["build-wasm"] }
watch = { watch = ["src", "../homotopy-core/src", "../homotopy-common/src", "../homotopy-graphics/src"] }

[tasks.dist-static]
script = '''
mkdir -p dist
echo "Cleaning old files"
find dist ! -name homotopy_web.js ! -name homotopy_web_bg.wasm -type f -exec rm -f {} +
cp -r static/* dist/
ls dist
'''

[tasks.dist-static-watch]
run_task = { name = ["dist-static"] }
watch = { watch = ["static"] }

[tasks.dist]
run_task = { name = ["build-wasm", "dist-static"] }

[tasks.clean]
clear = true
script = '''
rm -rf dist
cargo clean
'''

[tasks.devserver]
command = "devserver"
args = [
  "--path"
, "dist"
, "--header"
, "Cross-Origin-Opener-Policy=same-origin"
, "--header"
, "Cross-Origin-Embedder-Policy=require-corp"
]

[tasks.serve]
run_task = { name = ["devserver", "build-wasm-watch", "dist-static-watch"], parallel = true }
