name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=wasm32-unknown-unknown

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: Check formatting with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Lint with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Install and Build
        run: |
          cd homotopy-web
          npm install
          npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: homotopy-web/dist/


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout historical benchmarking data
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: olddist

      - name: Merge historical benchmarking data
        run: mv olddist/dev homotopy-web/dist/dev

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: homotopy-web/dist

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo bench
        run: CARGO_HUSKY_DONT_INSTALL_HOOKS=true cargo bench | tee output.txt

      - name: Store benchmark result
        uses: NickHu/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'criterion'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/master' }}
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@NickHu,@zrho'
